### PR TITLE
Reduce false positives

### PR DESCRIPTION
**Pull request by mobaig**
This monitor is triggering alerts in production right now whenever an exception occurs (e.g. - network errors). This PR adds logic to 

- rescue all exceptions
- send these to Errbit
- retry the email verification process a set number of times (default 5)
- exit 0 if all retries fail. 

The failure scenario we care about (a problem with the email verification) occurs when no exception is raised, doing exit(2) as required.

trello: https://trello.com/c/pfvrbnfZ/24-improve-email-alert-monitoring

### CODE REVIEW

**Comment by gpeng** [comment]
Looks good to me :+1:

**Comment by steventux** [comment]
:+1: looks good.

**Comment by dsingleton** [comment]
Taking a look, but CC @jennyd and @boffbowsh who were involved in the false-positive incidents over the weekend as well.

**Comment by dsingleton** [comment]
Overall, the approach looks 👍  to me. 

Catching _any and all_ exceptions makes me a little nervous, especially if we're exiting with `0` if _all_ retries fail. There's a risk that a persistent issue could go unnoticed - like a logic bug or problem with ENV configuration (like `GOOGLE_CLIENT_ID`).

**Comment by mobaig** [comment]
@dsingleton yeh, agreed that it'll be important to maintain visibility of these exceptions. This is mitigated by:

- sending all exceptions to Errbit.
- this tool being replaced / superseded in the short-term by an alternative implementation that's currently being worked on by Team TAP.

**Pull request merged**
